
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Derekahedron/Mythic-Tinkers/issues/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Derekahedron/Mythic-Tinkers"
logoFile="assets/${mod_id}/icon.png"
credits="This mod is dedicated to my two cats"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mantle"
mandatory=true
versionRange="${mantle_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tconstruct"
mandatory=true
versionRange="${tconstruct_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="citadel"
mandatory=true
versionRange="${citadel_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="alexscaves"
mandatory=true
versionRange="${alexscaves_version_range}"
ordering="NONE"
side="BOTH"